### ISSUE TITLE
🚀 Add MRU (Most Recently Used) Cache Algorithm to gofast

### ISSUE THREAD

**Issue by raghavgh** [raghavgh/gofast#12]
We’re currently missing an MRU (Most Recently Used) cache algorithm in our gofast caching library. If you’re interested in contributing to this feature, this is an excellent opportunity to have your code running in a live, production-ready library!

What’s MRU?

The MRU algorithm discards the most recently used items first, opposite to how LRU (Least Recently Used) works. It’s useful in certain scenarios where recently accessed data is less likely to be accessed again, such as when processing a stack of documents.

Why Pick This Up?

- You’ll write a full cache algorithm from scratch.
- A great opportunity to see your algorithm implemented in the real world and used by developers.
- Contributing to a growing Go project with multiple caching strategies.

What We Expect:

- Implement the MRU algorithm with thread safety.
- Ensure consistency with the rest of the library’s cache interface.
- Write unit tests to verify the correctness and efficiency of your implementation.
- Bonus: If you’re interested, add benchmarks to measure MRU performance compared to LRU and FIFO.

Get Started

- Fork the repository: [gofast](https://github.com/raghavgh/gofast)
- Check out the structure for existing cache implementations like LRU.
- Submit a pull request when you’re done, and we’ll be happy to review it!

Looking for Guidance?

Feel free to open a discussion if you need any help. We’d be happy to mentor or guide you through this contribution.

**Comment by abuzaforfagun** [comment]
I am interested in working on the issue.

**Comment by raghavgh** [comment]
> I am interested in working on the issue.

Assigned.

**Comment by raghavgh** [comment]
Hello @abuzaforfagun
Thank you for your valuable contribution.

Apologies for delay in review, I have added some comments, Please go through them, let me know if you have any question or concern.
Thanks

**Comment by raghavgh** [comment]
issue is resolved in [16](https://github.com/raghavgh/gofast/pull/16)

**Comment by raghavgh** [comment]
issue is resolved in [16](https://github.com/raghavgh/gofast/pull/16)
